### ISSUE TITLE
n ohdd suport

### ISSUE THREAD

**Issue by duhpajil** [shawnanastasio/ShawnOS#4]
i was try instal but no hd supoort

**Comment by duhpajil** [comment]
pls help it doesnot work

**Comment by drsn0w** [comment]
Hello, my name is Liam and I'm from drsn0w Ltd. Tech support. Can you please describe your problem in more detail?

**Comment by duhpajil** [comment]
i tri instal and no work

**Comment by drsn0w** [comment]
OK sir. I understand that you have tried to install ShawnOS and it didn't work. Thank you for clarifying that for me. In order to further assist you, I'm going to need some more information. Please provide the following:
- CPU model
- Motherboard model
- Detailed description of how you attempted to install ShawnOS
- Detailed description of the outcome of the attempted installation.

**Comment by duhpajil** [comment]
cpu; intel

**Comment by duhpajil** [comment]
cpu; intel
mobo: intel compat mobo
install process: downloded instal
instatltinon outcom: no work

**Comment by drsn0w** [comment]
Thank you for providing me with this extra information. 
With this information I was able to discern the problem with your installation.

Unfortunately, while ShawnOS supports the hardware you own, it does not support the user who installed it. PEBCAK.

Support case closed.

**Comment by duhpajil** [comment]
um what is prob i watn shawnos but no hd work you cant jsut close case like that

**Comment by duhpajil** [comment]
wow ih ate you i never want to see you ever again
